=== cahirwpz/libtpproto2-py/protocol.dtd
<!ELEMENT protocol (packet+)>
<!ATTRLIST protocol version CDATA #REQUIRED>
<!ELEMENT packet longname? direction? description? structure? note*>
<!ATTRLIST packet name ID #REQUIRED base IDREF #IMPLIED>
<!ELEMENT longname (#PCDATA)>
<!ELEMENT direction (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT structure (character | integer | string | enumeration | list | group)* >
<!ELEMENT character name longname description example note?>
<!ATTRLIST character size CDATA "1">
<!ELEMENT name (#PCDATA)>
<!ELEMENT example (#PCDATA)>
<!ELEMENT note (#PCDATA)>
<!ELEMENT element name longname description example note*>
<!ATTRLIST element type (signed|unsigned|semisigned) #REQUIRED size CDATA "32">
<!ELEMENT string name longname description example note*>
<!ELEMENT enumeration name longname description values example note*>
<!ATTRLIST enumeration type (signed|unsigned|semisigned) #REQUIRED size CDATA "32">
<!ELEMENT values value+>
<!ELEMENT value (#PCDATA)>
<!ATTRLIST value id CDATA #REQUIRED name CDATA #REQUIRED>
<!ELEMENT list name longname description structure example note*>
<!ELEMENT group name longname description structure example note*>

=== cahirwpz/libtpproto2-py/tests/xml/testprotocol014.xml
<?xml version="1.0"?>
<!DOCTYPE protocol SYSTEM "protocol.dtd">
<protocol version="TP03">
	<packet name="Fail" id="1">
		<description>A request has failed in some sort of way.</description>
		<structure>
			<enumeration type="unsigned" size="32" style="single">
				<name>code</name>
				<longname>Error Code</longname>
				<description>Text message of the error.</description>
				<values>
					<value id="0" name="Protocol">Protocol Error, Something went wrong with the protocol</value>
					<value id="1" name="Frame">Frame Error, One of the frames sent was bad or corrupted</value>
					<value id="2" name="UnavailablePermanently">Unavailable Permanently, This operation is unavailable</value>
					<value id="3" name="UnavailableTemporarily">Unavailable Temporarily, This operation is unavailable at this moment</value>
					<value id="4" name="NoSuchThing">No Such Thing, The object/order/message does not exist</value>
					<value id="5" name="PermissionDenied">Permission Denied, You don't have permission to do this operation</value>
					<value id="6" name="Gone">Object/order/message has gone.</value>
					<value id="7" name="FrameVersionNotSupported">The frame version is not supported</value>
					<value id="8" name="RequestTooBig">The requested reply is too big</value>
					<illegal-tag />
				</values>
			</enumeration>
		</structure>
	</packet>
</protocol>

=== cahirwpz/libtpproto2-py/tests/xml/testprotocol007.xml
<?xml version="1.0"?>
<!DOCTYPE protocol SYSTEM "protocol.dtd">
<protocol version="TP03">
	<packet name="Test">
		<direction>any</direction>
		<structure>
			<character size="4">
				<name>version</name>
				<longname>Packet Version</longname>
				<description><b>Always has value "TP03" ("TP" plus version number), no null terminator.</b></description>
				<example>TP03</example>
			</character>
		</structure>
	</packet>
</protocol>

=== cahirwpz/libtpproto2-py/tests/xml/testprotocol016.xml
<?xml version="1.0"?>
<!DOCTYPE protocol SYSTEM "protocol.dtd">
<protocol version="TP04">
<parameterset name="ObjectParams" />

<packet base="Header" name="Response">
	<direction>client</direction>
</packet>

<packet id="68" base="Response" name="ObjectDesc">
	<longname>Object Description</longname>
	<structure>
		<integer type="unsigned" size="32">
			<name>id</name>
			<longname>object type</longname>
			<description>object type</description>
			<subtype/>
		</integer>
		<string>
			<name>name</name>
			<longname>Name</longname>
			<description>Name of the object type.</description>
		</string>
		<string>
			<name>description</name>
			<longname>Description</longname>
			<description>Description of the object type.</description>
		</string>
		<integer type="unsigned" size="64">
			<name>modtime</name>
			<longname>Last Modification Time</longname>
			<description>The time at which this object description was last modified.</description>
		</integer>
		<list>
			<name>propertygroups</name>
			<longname>Property Groups</longname>
			<structure>
				<integer type="unsigned" size="32">
					<name>propertygroupid</name>
					<longname>Property Group ID</longname>
					<description>The ID for this Property Group.</description>
				</integer>
				<string>
					<name>groupname</name>
					<longname>Property Group Name</longname>
					<description>Name of this Property Group.</description>
				</string>
				<string>
					<name>groupdescription</name>
					<longname>Property Group Description</longname>
					<description>Description of this Property Group.</description>
				</string>
				<list>
					<name>parameters</name>
					<longname>Object Parameters</longname>
					<structure>
						<string>
							<name>name</name>
							<longname>argument name</longname>
							<description/>
						</string>
						<integer type="unsigned" size="32">
							<name>type</name>
							<longname>argument type ID</longname>
							<description>argument type ID</description>
							<subtype/>
						</integer>
						<string>
							<name>description</name>
							<longname>Description</longname>
							<description>Description of this parameter.</description>
						</string>
						<descparameter ref="ObjectParams" typefield="type">
							<name>extradata</name>
							<longname>extra data for this parameter</longname>
						</descparameter>
					</structure>
				</list>
			</structure>
		</list>
	</structure>
</packet>

<packet base="Response" name="Object" id="7">
	<longname>Object</longname>
	<structure>
		<integer type="unsigned" size="32" readonly="yes">
			<name>id</name>
			<longname>Object ID</longname>
			<description>The unquie identifier of the object.</description>
		</integer>
		<integer type="unsigned" size="32" readonly="yes">
			<name>otype</name>
			<longname>Object Type</longname>
			<description>The type of the object.</description>
			<subtype/>
		</integer>
		<string>
			<name>name</name>
			<longname>Object Name</longname>
			<description>The name of the object.</description>
		</string>
		<string>
			<name>desc</name>
			<longname>Object Description</longname>
			<description>A description of the object.</description>
		</string>
		<integer type="unsigned" size="32" readonly="yes">
			<name>parent</name>
			<longname>Parent Object ID</longname>
			<description>The ID of the object that contains this object.</description>
		</integer>
		<list>
			<name>contains</name>
			<longname>Contains</longname>
			<description>IDs of the objects contained by this object.</description>
			<structure>
				<integer type="unsigned" size="32" readonly="yes">
					<name>id</name>
					<longname>the ID</longname>
					<description>the ID</description>
				</integer>
			</structure>
		</list>
		<integer type="unsigned" size="64" readonly="yes">
			<name>modtime</name>
			<longname>Last Modification Time</longname>
			<description>The time at which this object was last modified.</description>
		</integer>
		<character size="16">
			<name>padding</name>
		</character>
		<useparameters ref="ObjectParams">
			<name>parameters</name>
			<longname>the object's parameters</longname>
			<typefield>otype</typefield>
			<typeframe name="ObjectDesc" idfield="id">
				<getlist name="propertygroups">
					<getlist>
						<getfield name="type"/>
					</getlist>
				</getlist>
			</typeframe>
		</useparameters>
	</structure>
</packet>
</protocol>

=== cahirwpz/libtpproto2-py/tests/xml/testprotocol021.xml
<?xml version="1.0"?>
<!DOCTYPE protocol SYSTEM "protocol.dtd">
<protocol version="TP04">
<parameterset name="ObjectParams" />

<packet base="Header" name="Response">
	<direction>client</direction>
</packet>

<packet id="68" base="Response" name="ObjectDesc">
	<longname>Object Description</longname>
	<structure>
		<integer type="unsigned" size="32">
			<name>id</name>
			<longname>object type</longname>
			<description>object type</description>
			<subtype/>
		</integer>
		<string>
			<name>name</name>
			<longname>Name</longname>
			<description>Name of the object type.</description>
		</string>
		<string>
			<name>description</name>
			<longname>Description</longname>
			<description>Description of the object type.</description>
		</string>
		<integer type="unsigned" size="64">
			<name>modtime</name>
			<longname>Last Modification Time</longname>
			<description>The time at which this object description was last modified.</description>
		</integer>
		<list>
			<name>propertygroups</name>
			<longname>Property Groups</longname>
			<structure>
				<integer type="unsigned" size="32">
					<name>propertygroupid</name>
					<longname>Property Group ID</longname>
					<description>The ID for this Property Group.</description>
				</integer>
				<string>
					<name>groupname</name>
					<longname>Property Group Name</longname>
					<description>Name of this Property Group.</description>
				</string>
				<string>
					<name>groupdescription</name>
					<longname>Property Group Description</longname>
					<description>Description of this Property Group.</description>
				</string>
				<list>
					<name>parameters</name>
					<longname>Object Parameters</longname>
					<structure>
						<string>
							<name>name</name>
							<longname>argument name</longname>
							<description/>
						</string>
						<integer type="unsigned" size="32">
							<name>type</name>
							<longname>argument type ID</longname>
							<description>argument type ID</description>
							<subtype/>
						</integer>
						<string>
							<name>description</name>
							<longname>Description</longname>
							<description>Description of this parameter.</description>
						</string>
						<descparameter ref="ObjectParams" typefield="type">
							<name>extradata</name>
							<longname>extra data for this parameter</longname>
						</descparameter>
					</structure>
				</list>
			</structure>
		</list>
	</structure>
</packet>

<packet base="Response" name="Object" id="7">
	<longname>Object</longname>
	<structure>
		<list>
			<name>contains</name>
			<longname>Contains</longname>
			<description>IDs of the objects contained by this object.</description>
			<structure>
				<useparameters ref="ObjectParams">
					<name>parameters</name>
					<longname>the object's parameters</longname>
					<typefield>otype</typefield>
					<typeframe idfield="id">
						<getlist name="propertygroups">
							<getlist name="parameters">
								<getfield name="type"/>
							</getlist>
						</getlist>
					</typeframe>
				</useparameters>
				<integer type="unsigned" size="32" readonly="yes">
					<name>id</name>
					<longname>the ID</longname>
					<description>the ID</description>
				</integer>
			</structure>
		</list>
	</structure>
</packet>
</protocol>

=== cahirwpz/libtpproto2-py/tests/xml/testprotocol003.xml
<?xml version="1.0"?>
<!DOCTYPE protocol SYSTEM "protocol.dtd">
<protocol version="TP03">
	<packet name="Header">
		<direction>any</direction>
		<structure>
			<character size="4">
				<name>version</name>
				<longname>Packet Version</longname>
				<description>Always has value "TP03" ("TP" plus version number), no null terminator.</description>
				<example>TP03</example>
			</character>
			<integer type="unsigned" size="32">
				<name>sequence</name>
				<longname>Sequence Number</longname>
				<description>An incrementing number "sequence number". The sequence number should always be one more then the previous frames sequence number.</description>
				<example>2345</example>
			</integer>
			<integer type="unsigned" size="32">
				<name>type</name>
				<longname>Type</longname>
				<description>Type of packet</description>
				<subtype />
				<example>2</example>
			</integer>
			<integer type="unsigned" size="32">
				<name>length</name>
				<longname>Length</longname>
				<description>Length of the packet</description>
				<example>32</example>
			</integer>
		</structure>
	</packet>

	<packet base="Header" name="Request"></packet>
	<packer base="Heade" name="Response"></packet>
</protocol>

=== cahirwpz/libtpproto2-py/tests/xml/testprotocol010.xml
<?xml version="1.0"?>
<!DOCTYPE protocol SYSTEM "protocol.dtd">
<protocol version="TP03">
	<packet name="Test">
		<direction>any</direction>
		<structure>
			<character size="4">
				<name>version</name>
				<longname>Packet Version</longname>
				<description>Always has value "TP03" ("TP" plus version number), no null terminator.</description>
				<example>TP03</example>
				<illegal-tag />
			</character>
		</structure>
	</packet>
</protocol>
